### ISSUE TITLE
ping entrypoint 

### ISSUE THREAD

**Issue by lfoppiano** [DataSeer/snapshot-api#1]
We need to add an entrypoint to the snapshot-api that respond only to our user, called /ping which check that both dataastet (/service/isalive ) and grobid (/api/isalive) are up

**Comment by NicolasKieffer** [comment]
# Health Monitoring Integration

## Added
- New health monitoring system with 4 endpoints:
  - `/ping` - Aggregates health status from all services
  - `/genshare/health` - Direct health check proxy to GenShare
  - `/grobid/health` - Direct health check proxy to GROBID
  - `/datastet/health` - Direct health check proxy to DataStet

- New configuration requirements:
  - Added health section in genshare.json
  - Created new config files: grobid.json and datastet.json
  - Each service requires a health endpoint configuration

## Modified
- Updated index.js to add new health monitoring routes
- Created healthController.js to manage health check logic
- Extended README.md with comprehensive health monitoring documentation

## Technical Details
- `/ping` response format:
```json
{
  "status": "healthy" | "unhealthy" | "error",
  "timestamp": "ISO-8601 date",
  "services": {
    "[service-name]": {
      "err": null | "error message",
      "request": "HTTP_METHOD URL",
      "response": {
        "status": HTTP_STATUS_CODE,
        "data": RESPONSE_DATA
      }
    }
  }
}
```
- Individual health endpoints act as direct proxies, returning unmodified service responses
- Error handling returns 500 status with service-specific error messages
- All endpoints require JWT authentication and are rate-limited

## Dependencies
- No new external dependencies required
